controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    # Controllers
    # joint_state_broadcaster:
    #   type: joint_state_broadcaster/JointStateBroadcaster

    base_controller:
      type: joint_trajectory_controller/JointTrajectoryController

# Base trajectory controller for position virtual joint
base_controller:
  ros__parameters:
    joints:
      - position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_partial_joints_goal: true
    open_loop_control: true
    allow_integration_in_goal_trajectories: true